### ISSUE TITLE
Did you try clustering directly on the ElMD distances instead of using dimensionality reduction?

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElMD#23]
The question came up and I wanted to check to see what you had tried already before diving in too deep myself.

**Comment by SurgeArrester** [comment]
I have tried it in the past, particularly on the binary compositions, and found it gave impressively poor results using DBSCAN and different values of epsilon, giving cluster labels that spead right across the embedded map. A proposed theory was that the non-negative sectional curvature that Wasserstein space possesses makes it unsuitable for direct application with clustering algorithms which assume some Euclidean measure of density. Given this past experience I typically cluster on embedded points because this does seem to work consistently.

I wouldn't say that I looked into it deeply enough to give a definitive answer though, and I'm not fully convinced by the above line of reasoning, but my Riemannian geometry isn't strong enough to argue the case for or against with any conviction. It could have been caused by a simple numerical issue and you may find that other clustering techniques or different datasets do cluster well in the metric space. We can see that the PCA embeddings have a fairly strong alignment with the true distances so it would be a bit surprising if techniques such as hierarchical clustering were to fail in the metric space completely, but these may require more human intervention to select different cutoff points to get "good" clusters which align with chemical judgement. 

Hope this helps!
