### ISSUE TITLE
Interesting follow-up work to ElMD within GRID

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElMD#27]
From "Predicting bulk modulus" section of https://doi.org/10.26434/chemrxiv-2022-9m4jh

> To address the absence of compositional information, we have therefore combined our GRID EMD with a similar compositional EMD, in a modified version of that demonstrated by Hargreaves et al.20 Our method represents the normalised elemental fractions as a 78- element vector in atomic number order (considering elements up to Bi, but excluding noble gases); taking SrTiO3 as a representative example would give values of 0.6, 0.2 and 0.2 at the 7th, 19th and 34th elements in this vector, respectively. Rather than ordering this vector by Pettifor scale and computing EMD directly as in [20], we instead introduce a pairwise dissimilarity metric (Fig. S3) between elements based on the statistical likelihood of species occurring within the same crystal structure (see methods).20 The advantage of this approach is that while the Pettifor scale assumes a constant distance between adjacent species, the substitutional (dis)similarity approach gives a more chemically meaningful metric. For example, the lanthanide series (La – Yb) covers a range of 14 steps on the Pettifor scale, while the dissimilarity approach gives a range of 0.4. In contrast, Na and F are adjacent on the Pettifor scale (one step), but have a dissimilarity of 4.38.

Repo: https://github.com/CumbyLab/gridrdf

Curious to hear your thoughts.

**Comment by sgbaird** [comment]
See also "Dissimilarity measure of local structure in inorganic crystals using Wasserstein distance to search for novel phosphors" https://doi.org/10.1080%2F14686996.2021.1899555

**Comment by SurgeArrester** [comment]
Hey Sterling,

I'm a big fan of the non-linear scale (although the default in ElMD is [the modified Pettifor](https://iopscience.iop.org/article/10.1088/1367-2630/18/9/093011/meta) scale which is based on statistical likelihood, so that probably wasn't clear enough in our paper). Dr. Cumby actually presented this work to our team a few months back and I was thinking of adding it to ElMD codebase at the time, but then thesis writing took over 🥳

I think it would take an achievable bit of tweaking to the supporting distance functions to take in a 2D elementwise matrix and not trip anything up in the backend. I recently came across [this linear scale](https://arxiv.org/abs/2007.00091) which I also quite like and was thinking of adding this to the set of dictionaries, so I'll probably do that feature at the same time.

Interestingly the approach they've taken with GRID is a really cool structural descriptor that was being simultaneously and independently investigated by a few members of our team in Liverpool, including ElMD developer @dwiddo. Check out their paper [here](https://match.pmf.kg.ac.rs/issues/m87n3/m87n3_529-559.html) and codebase [here](https://github.com/dwiddo/average-minimum-distance) for their implementation.

I hadn't seen the phosphors paper before so cheers for sending that over! That's a really interesting approach, and I can see how you could get more "structural fidelity" by restricting the search to structural descriptors that are fundamentally similar, as it's hard to say what the signal to noise ratio is for highly dissimilar structures. I wonder if it could be combined with something like [ChemEnv](https://journals.iucr.org/b/issues/2020/04/00/lo5066/lo5066.pdf) to get better input environments to search for against structural prototypes...
